
const plants = [
    {
        id: 1,
        name: "Alocasia Black Velvet",
        Light: "Low to Bright Indirect",
        Water: "Medium",
        price: "$25.00",
    },
     {
        id: 2,
        name: "Tropic Marianne",
        Light: "Low to Bright Indirect",
        Water: "Medium",
        price: "$45.00",
    },
     {
        id: 3,
        name: "Ficus Lyrata",
        Light: "Bright Indirect",
        Water: "Medium",
        price: "$49.00",
    },
     {
        id: 4,
        name: "Hoya Chelsea",
        Light: "Bright Indirect",
        Water: "Low to Medium",
        price: "$39.00",
    },
     {
        id: 5,
        name: "Cordyline 'Ruby'",
        Light: "Low to Bright Indirect",
        Water: "Medium",
        price: "$45.00",
    },
     {
        id: 6,
        name: "Calathea Green Lipstick",
        Light: "Low to Bright Indirect",
        Water: "Medium to High",
        price: "$55.00",
    },
    {
        id: 7,
        name: "Purple Shamrock",
        Light: "Low to Bright Indirect",
        Water: "Medium",
        price: "$25.00",
    },
    {
        id: 8,
        name: "Sansevieria Silver Princess",
        Light: "Low to Bright Indirect",
        Water: "Low",
        price: "$25.00",
    },
    {
        id: 9,
        name: "Calathea Misto",
        Light: "Low to Bright Indirect",
        Water: "Medium to High",
        price: "$98.00",
    },
    {
        id: 10,
        name: "Hoya Green Ghost",
        Light: "Bright Indirect",
        Water: "Low to Medium",
        price: "$49.00",
    },
    {
        id: 11,
        name: "Sansevieria Sunshine",
        Light: "Low to Bright Indirect",
        Water: "Low",
        price: "$19.50",
    },
     {
        id: 12,
        name: "Farfugium 'Firefly'",
        Light: "Low to Bright Indirect",
        Water: "Medium",
        price: "$32.00",
    },
     {
        id: 13,
        name: "Hoya rangsan",
        Light: "Bright Indirect",
        Water: "Low to Medium",
        price: "$59.00",
    },
     {
        id: 14,
        name: "Chinese Evergreen 'Butterfly'",
        Light: "Low to Medium",
        Water: "Medium",
        price: "$25.00",
    },
     {
        id: 15,
        name: "Philodendron 'Summer Glory'",
        Light: "Low to Bright Indirect",
        Water: "Medium",
        price: "$110.00",
    },
     {
        id: 16,
        name: "Hoya Australis Hoop",
        Light: "Bright Indirect",
        Water: "Low to Medium",
        price: "$39.00",
    },
    {
        id: 17,
        name: "Pothos Silvery Anne",
        Light: "Medium to Bright Indirect",
        Water: "Low to Medium",
        price: "$22.50",
    },
    {
        id: 18,
        name: "Spider Plant Hawaiian",
        Light: "Medium Bright",
        Water: "Medium",
        price: "$18.50",
    },
    {
        id: 19,
        name: "Monstera deliciosa",
        Light: "Low to Bright Indirect",
        Water: "Medium",
        price: "$49.00",
    },
    {
        id: 20,
        name: "Winged Pitcher Plant",
        Light: "Bright Indirect",
        Water: "Low to Medium",
        price: "$69.00",
    }
]